### PR TITLE
updated jest and eslint

### PR DESCRIPTION
**Pull request by oskar-fredriksson-fujitsu**

### CODE REVIEW

**Comment by svenssonaxel** [comment]
Incrementing the minor version seems strange, as no functionality is added. Perhaps incrementing the patch version is more appropriate?

**Comment by TobiasOlofsson88** [comment]
> Incrementing the minor version seems strange, as no functionality is added. Perhaps incrementing the patch version is more appropriate?

@svenssonaxel ESLint v7.x and Jest v26.x is EOL, major version bump seems resonable.

**Comment by TobiasOlofsson88** [comment]
@oskar-fredriksson-fujitsu two failing tests. Probably due to running on node 22. It has previously only been tested on node 14.

image

**Comment by janghede** [comment]
Remember you can also use git bash in vscode to execute the script files. I'm finding that the tests pass, but we need to migrate to a new type of config file for eslint:
image

**Comment by svenssonaxel** [comment]
```
 FAIL  ./version.test.js
  ● Version

    expect(received).toBe(expected) // Object.is equality

    Expected: "0.6.1"
    Received: "0.5.1"

      11 |
      12 | test("Version", () => {
    > 13 |   expect(version_in_package_lock_json).toBe(version_in_package_json);
         |                                        ^
```
Here's after running `./script npm-ci`. I think the lockfile needs updating.

**Comment by svenssonaxel** [comment]
> @svenssonaxel ESLint v7.x and Jest v26.x is EOL, major version bump seems resonable.

Sure, I guess that breaks backwards compatibility in a way.

**Comment by svenssonaxel** [comment]
> @oskar-fredriksson-fujitsu two failing tests. Probably due to running on node 22. It has previously only been tested on node 14.

It looks like the function is time zone aware but the test case is not. I assume the 9h difference match the time zone difference between Stockholm and your local machine? People in Sweden can reproduce the test failure like this: `TZ=US/Pacific ./script run-tests`.

If you want to keep the current behavior where the formatting functions use the local time zone, and just want to fix the test, here's a quick-fix (although I don't know if this works on Windows):

```diff
diff --git a/script b/script
index f8ef833..c42830a 100755
--- a/script
+++ b/script
@@ -25,7 +25,7 @@ npm-ci() {
 }
 
 run-tests() {
-    npx jest
+    TZ=Europe/Stockholm npx jest # Some tests assume Stockholm time zone.
     npx eslint .
     echo-green done testing
 }
```

**Review by TobiasOlofsson88 — APPROVED** [review]

**Pull request merged**
